[package]
name = "devcat"
version = "0.1.3"
authors = ["Lucian BLETAN <neuraluc@gmail.com>"]
edition = "2024"
description = "A micro-version control system for your AI development loop."
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/devcat"

homepage = "https://github.com/gni/devcat"
repository = "https://github.com/gni/devcat"

categories = ["command-line-utilities", "development-tools"]
keywords = ["llm", "code", "ollama", "oss", "ai"]

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6.0", features = ["derive"] }
env_logger = "0.11.10"
globset = "0.4.18"
humantime = "2.3.0"
ignore = "0.4.25"
log = "0.4.29"
notify = "8.2.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
similar = "2.7.0"
thiserror = "2.0.18"
toml = "0.9.12"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"